defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Chris Grigsby
subtitle: No hookups. 

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: ""

# Side Menu Links
menu:
  - text: About Me
    link: /
    icon: ""

    #text: My Resume
    #link: /resume
    #icon: ""

  - text: Pentest Lab Writeups
    link: /writeups
    icon: ""

  - text: OSCP Notes
    link: /oscp_notes
    icon: ""

  - text: Blog
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/chris-a-grigsby  
    icon: fab fa-linkedin

    #name: gmail
    #link: https://mailto:cagrigsby@gmail.com
    #icon: fab fa-google

  - name: github
    link: https://github.com/pentestpop
    icon: fab fa-github-square

  - name: mastodon
    link: https://techhub.social/@poppop
    icon: fab fa-mastodon

  - name: tryhackme
    link: https://tryhackme.com/p/grica421
    icon: /assets/icons/tryhackme.png
    
  - name: onlyfans
    link: https://www.reddit.com/r/LucidDreaming/comments/pwo63h/the_ultimate_no_bs_guide_to_lucid_dreaming/
    icon: /assets/icons/onlyfans.png

# trying to add a collection for Writeups
collections:
  writeups:
    output: true
    permalink: /writeups/:path/

#adding rouge
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
